### ISSUE TITLE
"rhs" is read only in cell 44

### ISSUE THREAD

**Issue by stephenhallfr-zz** [IBMDecisionOptimization/tutorials#2]
Hi,

When I import the notebook in DSX Python 2.6  with spark 2.0 the cell 44 return an error.
The linear constraint seams to be only read only.
here is the error message: 
AttributeErrorTraceback (most recent call last)
<ipython-input-44-53a1c3dc7866> in <module>()
      1 res = []
      2 for i in range(20):
----> 3     ct.rhs = availableBudget+1000*i
      4     s = mdl.solve()
      5     assert s, "No Solution !!!"

AttributeError: 'LinearConstraint' object attribute 'rhs' is read-only

**Comment by vberaudi** [comment]
You need to update your docplex version.
